module mockito.base {
    requires java.base;
    requires junit;
    requires org.objenesis;
    requires java.instrument;
    requires net.bytebuddy;
    requires net.bytebuddy.agent;
    requires mockito.external;
    exports org.mockito.internal.util to mockito.test;
    exports org.mockito.internal.verification to mockito.test;
    exports org.mockito.internal.matchers to mockito.test;
    exports org.mockito.internal.stubbing.answers to mockito.test;
    exports org.mockito.internal.listeners to mockito.test;
    exports org.mockito.internal.debugging to mockito.test;
    exports org.mockito.internal.invocation to mockito.test;
    exports org.mockito.internal.invocation.mockref to mockito.test;
    exports org.mockito.internal to mockito.test;
    exports org.mockito.internal.runners to mockito.test;
    exports org.mockito.internal.matchers.text to mockito.test;
    exports org.mockito.internal.exceptions.stacktrace to mockito.test;
    exports org.mockito.internal.configuration.injection to mockito.test;
    exports org.mockito.internal.configuration to mockito.test;
    exports org.mockito.internal.creation to mockito.test;
    exports org.mockito.internal.handler to mockito.test;
    exports org.mockito.internal.progress to mockito.test;
    exports org.mockito.internal.framework to mockito.test;
    exports org.mockito;
    exports org.mockito.configuration;
    exports org.mockito.exceptions.base;
    exports org.mockito.exceptions.misusing;
    exports org.mockito.exceptions.stacktrace;
    exports org.mockito.exceptions.verification;
    exports org.mockito.hamcrest;
    exports org.mockito.instance;
    exports org.mockito.invocation;
    exports org.mockito.junit;
    exports org.mockito.listeners;
    exports org.mockito.mock;
    exports org.mockito.plugins;
    exports org.mockito.quality;
    exports org.mockito.runners;
    exports org.mockito.stubbing;
    exports org.mockito.verification;
    exports org.mockito.exceptions.verification.junit;

}
